// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZrwIy6xVdymPP1XFzaWBQVOZBNjYahU4',
    appId: '1:238859431374:web:3522e93e369570ef9a0f9f',
    messagingSenderId: '238859431374',
    projectId: 'taskq-app-project',
    authDomain: 'taskq-app-project.firebaseapp.com',
    storageBucket: 'taskq-app-project.appspot.com',
    measurementId: 'G-M5F4SFFNEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsqNAmLVzto4bDhXSwXuq2frtnfIYtA8g',
    appId: '1:238859431374:android:8eea7a24a672243b9a0f9f',
    messagingSenderId: '238859431374',
    projectId: 'taskq-app-project',
    storageBucket: 'taskq-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyComYP4rpgq_7oGRSuSqT8UjJiE_BpN5kk',
    appId: '1:238859431374:ios:300f764b8eeb9b439a0f9f',
    messagingSenderId: '238859431374',
    projectId: 'taskq-app-project',
    storageBucket: 'taskq-app-project.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyComYP4rpgq_7oGRSuSqT8UjJiE_BpN5kk',
    appId: '1:238859431374:ios:300f764b8eeb9b439a0f9f',
    messagingSenderId: '238859431374',
    projectId: 'taskq-app-project',
    storageBucket: 'taskq-app-project.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZrwIy6xVdymPP1XFzaWBQVOZBNjYahU4',
    appId: '1:238859431374:web:33b9cdc0368eaf8f9a0f9f',
    messagingSenderId: '238859431374',
    projectId: 'taskq-app-project',
    authDomain: 'taskq-app-project.firebaseapp.com',
    storageBucket: 'taskq-app-project.appspot.com',
    measurementId: 'G-HG9P3N00R5',
  );
}
