class Quotes {
  List<String> dailyquotes = [
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Hard work beats talent when talent doesn't work hard.",
    "The only way to do great work is to love what you do.",
    "Don't watch the clock; do what it does. Keep going.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "You are never too old to set another goal or to dream a new dream.",
    "Quality is not an act, it is a habit.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Believe you can and you're halfway there.",
    "It does not matter how slowly you go as long as you do not stop.",
    "I find that the harder I work, the more luck I seem to have.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "The only place where success comes before work is in the dictionary.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Opportunities don't happen, you create them.",
    "Strive not to be a success, but rather to be of value.",
    "You miss 100% of the shots you don't take.",
    "The only thing worse than starting something and failing... is not starting something.",
    "Don't be afraid to give up the good to go for the great.",
    "Don't be busy, be productive.",
    "Your limitation—it's only your imagination.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Success is not just about working hard, but working smart.",
    "Don't wait for opportunity, create it.",
    "Work hard in silence, let success make the noise.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Don't stop when you're tired. Stop when you're done.",
    "Dream it. Wish it. Do it.",
    "Don't be afraid to start over. It's a brand new opportunity to rebuild what you truly want.",
    "The key to success is to focus on goals, not obstacles.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Don't let yesterday take up too much of today.",
    "Little things make big days.",
    "It's not whether you get knocked down, it's whether you get up.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Dream bigger. Do bigger.",
    "You are capable of more than you know.",
    "Everything you can imagine is real.",
    "Don't wait. The time will never be just right.",
    "Don't stop until you're proud.",
    "You don't have to be great to start, but you have to start to be great.",
    "In the middle of difficulty lies opportunity.",
    "The only way to do great work is to love what you do.",
    "The harder you work, the luckier you get."
  ];
}
